[package]
name = "gfetch"
version = "0.1.0"
authors = ["Eric Huss"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
git2 = "0.13.8"
anyhow = "1.0.31"
openssl = {version="0.10.55", features=["vendored"]}
